applications:
  - name: "openbao"
    role_name: "openbao"
    domain: "vault.internal"
    target_ip: "{{ ansible_host }}"
    target_port: 8200
    homepage:
      name: OpenBao
      description: "Secrets Management"
      group: "Security"
      icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/openbao.svg

openbao_image: "openbao/openbao:2.5.0"