- name: Create Vaultwarden volumes
  community.docker.docker_volume:
    name: vaultwarden-data

- name: Create Vaultwarden container
  community.docker.docker_container:
    name: vaultwarden
    image: "{{ vaultwarden_image }}"
    env:
      DOMAIN: "{{ vaultwarden_domain }}"
    volumes:
      - vaultwarden-data:/data:rw
    ports:
    - "8080:80"
    restart_policy: unless-stopped
