applications:
  - name: "forgejo"
    role_name: "forgejo-headless"
    domain: "forgejo.internal"
    target_ip: "{{ ansible_host }}"
    target_port: 3000

forgejo_version: "13.0.4"

# App configuration
forgejo_db_type: "sqlite3"
forgejo_app_name: "Forgejo"
forgejo_run_mode: "prod"
forgejo_http_port: 3000

# secrets
forgejo_domain: "{{ lookup('community.hashi_vault.vault_kv2_get', 'proxmox/forgejo-lxc/secrets', engine_mount_point='ansible').data.data.forgejo_domain }}"
forgejo_admin_user: "{{ lookup('community.hashi_vault.vault_kv2_get', 'proxmox/forgejo-lxc/secrets', engine_mount_point='ansible').data.data.admin_user }}" 
forgejo_admin_password: "{{ lookup('community.hashi_vault.vault_kv2_get', 'proxmox/forgejo-lxc/secrets', engine_mount_point='ansible').data.data.admin_password }}"
forgejo_admin_email: "{{ lookup('community.hashi_vault.vault_kv2_get', 'proxmox/forgejo-lxc/secrets', engine_mount_point='ansible').data.data.admin_email }}"
forgejo_secret_key: "{{ lookup('community.hashi_vault.vault_kv2_get', 'proxmox/forgejo-lxc/secrets', engine_mount_point='ansible').data.data.forgejo_secret_key }}"
