---
applications:
  - name: "authentik_core"
    role_name: "authentik"
    domain: "auth.internal"
    target_ip: "{{ ansible_host }}"
    target_port: 9443
    homepage:
      name: Authentik
      description: "Identity and Access Management"
      group: "Security"
      icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/authentik.svg

## Images
authentik_image: "ghcr.io/goauthentik/server:2026.2.2"
authentik_postgres_image: "docker.io/library/postgres:16-alpine"
authentik_redis_image: "docker.io/library/redis:8.6.2-alpine"
cloudflare_tunnel_image: "cloudflare/cloudflared:2026.3.0"

## Authentik configuration
authentik_secret_key: "{{ lookup('community.hashi_vault.vault_kv2_get', 'proxmox/sec-prod-01/secrets', engine_mount_point='ansible').data.data.authentik_secret }}"
authentik_pg_pass: "{{ lookup('community.hashi_vault.vault_kv2_get', 'proxmox/sec-prod-01/secrets', engine_mount_point='ansible').data.data.postgres_pass }}"

## Cloudflare Tunnel Configuration
cloudflare_tunnel_token: "{{ lookup('community.hashi_vault.vault_kv2_get', 'proxmox/sec-prod-01/secrets', engine_mount_point='ansible').data.data.tunnel_token }}"
enable_cloudflare_tunnel: true