apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: default
spec:
  containers:
  - image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
    name: spot
    resources:
      requests:
        cpu: "1"
        memory: 256M
      limits:
        cpu: "1"
        memory: 256M
#  nodeSelector:
    # label-key : label-value