---
# ==============================================================================
# APPLICATION ROUTING & DNS
# proxy-server (caddy) and dns-server (technitium) roles will iterate dynamically over this list.
# ==============================================================================
applications:

  ###################################
  # Homepage
  ###################################
  - app_name: "homepage"
    role_name: "homepage"
    domain: "home.internal"
    target_ip: "{{ ansible_host }}"
    target_port: 3001
    homepage_group: "all"
    custom_services:
      - name: "Proxmox"
        group: "Infrastructure"
        href: "https://proxmox.internal:8006"
        description: "Proxmox Virtual Environment"
        icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/proxmox.svg"

      - name: Technitium DNS
        description: Technitium DNS Server 01
        group: DNS
        icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/technitium.webp"
        href: "http://dns.internal:5380"

      - name: caddy
        group: Network
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/caddy.svg
        description: HTTP Reverse Proxy (NO UI)
        href: ""
      - name: Uptime Kuma
        group: Network
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/uptime-kuma.svg
        description: Uptime Monitoring
        href: ""
      - name: Uptime Robot
        group: Network
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/uptimerobot.svg
        description: Uptime Monitoring
        href: ""
      - name: OpenSpeedTest
        group: Network
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/openspeedtest.svg
        description: Speed Test
        href: ""

      - name: Victoria Metrics
        group: Monitoring
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/victoriametrics.svg
        description: Time series Database
        href: ""
      - name: Grafana Loki
        group: Monitoring
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/loki.svg
        href: ""
        description: Log Storage
      - name: Scrutiny
        group: Monitoring
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/scrutiny.svg
        href: ""
        description: Drive Health

      - name: TrueNAS
        group: Storage
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/truenas.svg
        href: ""
        description: NAS Storage
      - name: RustFS
        group: Storage
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/rustfs.svg
        href: ""
        description: Object Storage
      - name: MinIO
        group: Storage
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/minio.svg
        href: ""
        description: Object Storage (Archived)

      - name: Tailscale
        description: VPN and Remote Access
        group: Remote Access
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/tailscale.svg
        href: "https://login.tailscale.com"
      - name: Code Server
        group: Remote Access
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/code-server.webp
        href: ""
        description: VSCode in the browser

      - name: pgAdmin
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/pgadmin.svg
        href: ""
        group: Databases
        description: PostgreSQL Management
      - name: Adminer
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/adminer.svg
        href: ""
        group: Databases
        description: Database Management
      - name: Mongo Express
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/mongodb.svg
        href: ""
        group: Databases
        description: MongoDB Management
      - name: phpMyAdmin
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/phpmyadmin.svg
        href: ""
        group: Databases
        description: MySQL Management
      - name: DBgate
        icon: /icons/dbgate.png
        href: ""
        group: Databases
        description: Database Management
      - name: Databasus
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/databasus.svg
        href: ""
        group: Databases
        description: Database Management
      - name: Adminer
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/adminer.svg
        href: ""
        group: Databases
        description: Database Management

      - name: Wazuh
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/wazuh.svg
        href: ""
        group: Security
        description: "Security Information and Event Management (SIEM)"
      - name: Opnsense
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/opnsense.svg
        href: ""
        group: Security
        description: Firewall and Network Security

      - name: BookStack
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/bookstack.svg
        href: ""
        group: Documents
        description: Wiki and Documentation

      - name: Rancher
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/rancher.svg
        href: ""
        group: Containers
        description: Kubernetes
      - name: Dozzle
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/dozzle.svg
        href: ""
        group: Containers
        description: Container Logs

      - name: Jellyfin
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/jellyfin.svg
        href: ""
        group: Media
        description: Media Server
      - name: Immich
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/immich.svg
        href: ""
        group: Media
        description: Photo Management
      - name: Plex
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/plex.svg
        href: ""
        group: Media
        description: Media Server
      - name: Tautulli
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/tautulli.svg
        href: ""
        group: Media
        description: Plex Analytics

  - app_name: "homepage-02"
    role_name: "homepage"
    domain: "home-monitoring.internal"
    target_ip: "{{ ansible_host }}"
    target_port: 3002
    homepage_group: "monitoring"

  ########################################################
  # Other Applications
  ########################################################
  - name: "monitoring"
    role_name: "monitoring_stack"
    domain: "grafana.internal"
    target_ip: "{{ ansible_host }}"
    target_port: 3000
    homepage:
      name: Grafana
      description: "Data visualization and monitoring platform"
      group: "Monitoring"
      icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/grafana.svg
      instance:
        - monitoring

  - name: "paperless"
    role_name: "paperless_ngx"
    domain: "paperless.internal"
    target_ip: "{{ ansible_host }}"
    target_port: 8000
    homepage:
      name: Paperless NGX
      description: "Document management system with OCR capabilities"
      group: "Documents"
      icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/paperless-ngx.svg

  - name: "linkwarden"
    role_name: "linkwarden"
    domain: "linkwarden.internal"
    target_ip: "{{ ansible_host }}"
    target_port: 3300
    homepage:
      name: Linkwarden
      description: "Link Management and Bookmarking"
      group: "Tools"
      icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/linkwarden.webp

  - name: "tools_stack"
    role_name: "tools_stack"
    stack_services:
      - name: "it-tools"
        domain: "ittools.internal"
        target_ip: "{{ ansible_host }}"
        target_port: 8080
        homepage:
          name: it-tools
          description: "IT Tools and Utilities"
          group: "Tools"
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/it-tools.svg
      - name: "cyberchef"
        domain: "cyberchef.internal"
        target_ip: "{{ ansible_host }}"
        target_port: 8081
        homepage:
          name: cyberchef
          description: ""
          group: "Tools"
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/cyberchef.svg
      - name: "diagrams"
        domain: "diagrams.internal"
        target_ip: "{{ ansible_host }}"
        target_port: 8082
        homepage:
          name: diagrams
          description: ""
          group: "Tools"
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/diagrams-net.svg
      - name: "excalidraw"
        domain: "excalidraw.internal"
        target_ip: "{{ ansible_host }}"
        target_port: 8083
        homepage:
          name: excalidraw
          description: ""
          group: "Tools"
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/excalidraw.svg
      - name: "bentopdf"
        domain: "bentopdf.internal"
        target_ip: "{{ ansible_host }}"
        target_port: 8084
        homepage:
          name: bentopdf
          description: ""
          group: "PDF Tools"
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/bentopdf.svg
      - name: "plantuml"
        domain: "plantuml.internal"
        target_ip: "{{ ansible_host }}"
        target_port: 8085
        homepage:
          name: plantuml
          description: ""
          group: "Tools"
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/plantuml.svg
      - name: "mermaid"
        domain: "mermaid.internal"
        target_ip: "{{ ansible_host }}"
        target_port: 8086
        homepage:
          name: mermaid
          description: ""
          group: "Tools"
          icon: ""
      - name: "convertx"
        domain: "convertx.internal"
        target_ip: "{{ ansible_host }}"
        target_port: 8087
        homepage:
          name: convertx
          description: ""
          group: "Tools"
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/convertx.webp
      - name: "omni-tools"
        domain: "omni-tools.internal"
        target_ip: "{{ ansible_host }}"
        target_port: 8088
        homepage:
          name: Omni Tools
          description: IT Tools and Utilities
          group: "Tools"
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/omni-tools.webp
      - name: "bytestash"
        domain: "bytestash.internal"
        target_ip: "{{ ansible_host }}"
        target_port: 8089
        homepage:
          name: bytestash
          description: "Code snippet manager"
          group: "Tools"
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/bytestash.svg
      - name: "memos"
        domain: "memos.internal"
        target_ip: "{{ ansible_host }}"
        target_port: 8090
        homepage:
          name: memos
          description: "Note Taking and Personal Knowledge Management"
          group: "Tools"
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/memos.svg
      - name: "freshrss"
        domain: "freshrss.internal"
        target_ip: "{{ ansible_host }}"
        target_port: 8091
      # - name: "booklore"
      #   domain: "booklore.internal"
      #   target_ip: "{{ ansible_host }}"
      #   target_port: 8092
      #   homepage:
      #    name: booklore
      #    description: "Book and Reading Management"
      #    group: "Documents"
      #    icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/booklore.svg
      - name: "jotty"
        domain: "jotty.internal"
        target_ip: "{{ ansible_host }}"
        target_port: 8093
        homepage:
          name: jotty
          description: "Note Taking and Personal Knowledge Management"
          group: "Tools"
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/jotty.svg

# ==============================================================================
# 2. IMAGE VERSIONS & CONFIGURATIONS (Public/Safe GitOps Data)
# ==============================================================================
# Tools Stack
tools_stack_it_tools_image: "corentinth/it-tools:2024.10.22-7ca5933"
tools_stack_cyberchef_image: "ghcr.io/gchq/cyberchef:10.22.1"
tools_stack_drawio_image: "jgraph/drawio:29.6.6"
tools_stack_bentopdf_image: "ghcr.io/alam00000/bentopdf-simple:2.7.0"
tools_stack_plantuml_image: "plantuml/plantuml-server:v1.2026.2"
tools_stack_convertx_image: "ghcr.io/c4illin/convertx:latest"
tools_stack_omni_tools_image: "iib0011/omni-tools:0.6"
tools_stack_bytestash_image: "ghcr.io/jordan-dalby/bytestash:1.5.11"
tools_stack_memos_image: "neosmemo/memos:0.26.2"
tools_stack_freshrss_image: "freshrss/freshrss:latest"
# tools_stack_booklore_image: "ghcr.io/booklore-app/booklore:v2.2.1"
tools_stack_booklore_mariadb_image: "lscr.io/linuxserver/mariadb:11.4.9"
tools_stack_jotty_image: "ghcr.io/fccview/jotty:1.21.1"

# Monitoring Stack
monitoring_role: "server"
monitor_docker: true
monitoring_stack_alloy_image: "grafana/alloy:v1.14.2"
monitoring_stack_victoriametrics_image: "victoriametrics/victoria-metrics:v1.138.0-scratch"
monitoring_stack_loki_image: "grafana/loki:3.7"
monitoring_stack_grafana_image: "grafana/grafana:12.4.2"
monitoring_stack_pve_exporter_image: "prompve/prometheus-pve-exporter:3.8.2"
monitoring_stack_cadvisor_image: "ghcr.io/google/cadvisor:0.56.2"

# Linkwarden
linkwarden_image: "ghcr.io/linkwarden/linkwarden:v2.13.5"

# Paperless-ngx
paperless_webserver_image: "ghcr.io/paperless-ngx/paperless-ngx:2.20.13"
paperless_broker_image: "docker.io/library/redis:8.6.2"
paperless_db_image: "docker.io/library/postgres:17.9"
paperless_allowed_hosts: "paperless.internal"
paperless_url: "https://paperless.internal"

# ==============================================================================
# 3. OPENBAO / HASHICORP VAULT LOOKUPS
# Replaces your local vault.yml and hardcoded plaintext tokens.
# The VAULT_TOKEN environment variable is injected by the GitHub Actions runner.
# ==============================================================================
# Tools Stack Secrets
bytestash_jwt_secret: "{{ lookup('community.hashi_vault.vault_kv2_get', 'proxmox/srv-prod-01/secrets', engine_mount_point='ansible').data.data.bytestash_jwt_secret }}"
booklore_db_root_password: "{{ lookup('community.hashi_vault.vault_kv2_get', 'proxmox/srv-prod-01/secrets', engine_mount_point='ansible').data.data.booklore_db_root_password }}"
booklore_db_password: "{{ lookup('community.hashi_vault.vault_kv2_get', 'proxmox/srv-prod-01/secrets', engine_mount_point='ansible').data.data.booklore_db_password }}"

# # Monitoring Stack Secrets
grafana_admin_password: "{{ lookup('community.hashi_vault.vault_kv2_get', 'proxmox/srv-prod-01/secrets', engine_mount_point='ansible').data.data.grafana_admin_password }}"
pve_exporter_token_value: "{{ lookup('community.hashi_vault.vault_kv2_get', 'proxmox/srv-prod-01/secrets', engine_mount_point='ansible').data.data.pve_exporter_token_value }}"


# # Linkwarden Secrets
linkwarden_postgres_password: "{{ lookup('community.hashi_vault.vault_kv2_get', 'proxmox/srv-prod-01/secrets', engine_mount_point='ansible').data.data.linkwarden_postgres_password }}"
linkwaren_meili_key: "{{ lookup('community.hashi_vault.vault_kv2_get', 'proxmox/srv-prod-01/secrets', engine_mount_point='ansible').data.data.linkwarden_meili_key }}"
linkwarden_nextauth_secret: "{{ lookup('community.hashi_vault.vault_kv2_get', 'proxmox/srv-prod-01/secrets', engine_mount_point='ansible').data.data.linkwarden_nextauth_secret }}"

# # Paperless Secrets
paperless_admin_user: "{{ lookup('community.hashi_vault.vault_kv2_get', 'proxmox/srv-prod-01/secrets', engine_mount_point='ansible').data.data.paperless_admin_user }}"
paperless_admin_password: "{{ lookup('community.hashi_vault.vault_kv2_get', 'proxmox/srv-prod-01/secrets', engine_mount_point='ansible').data.data.paperless_admin_password }}"
paperless_admin_email: "{{ lookup('community.hashi_vault.vault_kv2_get', 'proxmox/srv-prod-01/secrets', engine_mount_point='ansible').data.data.paperless_admin_email }}"
paperless_secret_key: "{{ lookup('community.hashi_vault.vault_kv2_get', 'proxmox/srv-prod-01/secrets', engine_mount_point='ansible').data.data.paperless_secret_key }}"
paperless_db_user: "{{ lookup('community.hashi_vault.vault_kv2_get', 'proxmox/srv-prod-01/secrets', engine_mount_point='ansible').data.data.paperless_db_user }}"
paperless_db_password: "{{ lookup('community.hashi_vault.vault_kv2_get', 'proxmox/srv-prod-01/secrets', engine_mount_point='ansible').data.data.paperless_db_password }}"

# # DNS API Variables (Moved from playbook)

technitium_api_url: "{{ lookup('community.hashi_vault.vault_kv2_get', 'proxmox/srv-prod-01/secrets', engine_mount_point='ansible').data.data.technitium_api_url }}"
technitium_token: "{{ lookup('community.hashi_vault.vault_kv2_get', 'proxmox/srv-prod-01/secrets', engine_mount_point='ansible').data.data.technitium_token }}"